### ISSUE TITLE
`window is not defined` even with the dynamic import on Next.js

### ISSUE THREAD

**Issue by toku-sa-n** [Gherciu/react-p5#94]
Hello. I'm trying to use `react-p5` with Next.js, but can't resolve the `window is not defined` error.

```
> zakuaku-summer-festival@0.1.0 dev
> next dev

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- event compiled client and server successfully in 161 ms (20 modules)
- wait compiling...
- event compiled client and server successfully in 158 ms (20 modules)
- wait compiling /page (client and server)...

warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
warn - https://tailwindcss.com/docs/content-configuration
- event compiled client and server successfully in 969 ms (393 modules)
- wait compiling...
- event compiled successfully in 80 ms (209 modules)
- error node_modules/react-p5/build/index.js (1:481675) @ requestAnimationFrame
- error unhandledRejection: Error [ReferenceError]: window is not defined
    at e.exports.271.core-js/modules/es.array.filter (webpack-internal:///(sc_server)/./node_modules/react-p5/build/index.js:19487:1597)
    at o (webpack-internal:///(sc_server)/./node_modules/react-p5/build/index.js:65:37)
    at eval (webpack-internal:///(sc_server)/./node_modules/react-p5/build/index.js:66:40)
    at e.exports.260../constants (webpack-internal:///(sc_server)/./node_modules/react-p5/build/index.js:18073:53)
    at o (webpack-internal:///(sc_server)/./node_modules/react-p5/build/index.js:65:37)
    at eval (webpack-internal:///(sc_server)/./node_modules/react-p5/build/index.js:66:40)
    at e.exports.245../accessibility/color_namer (webpack-internal:///(sc_server)/./node_modules/react-p5/build/index.js:16643:45)
    at o (webpack-internal:///(sc_server)/./node_modules/react-p5/build/index.js:65:37)
    at e (webpack-internal:///(sc_server)/./node_modules/react-p5/build/index.js:71:62)
    at Object.eval (webpack-internal:///(sc_server)/./node_modules/react-p5/build/index.js:73:19)
    at Object.eval (webpack-internal:///(sc_server)/./node_modules/react-p5/build/index.js:26669:16)
    at r (webpack-internal:///(sc_server)/./node_modules/react-p5/build/index.js:14:25)
    at Module.eval (webpack-internal:///(sc_server)/./node_modules/react-p5/build/index.js:26678:43)
    at r (webpack-internal:///(sc_server)/./node_modules/react-p5/build/index.js:14:25)
    at eval (webpack-internal:///(sc_server)/./node_modules/react-p5/build/index.js:47:22)
    at eval (webpack-internal:///(sc_server)/./node_modules/react-p5/build/index.js:48:6)
    at eval (webpack-internal:///(sc_server)/./node_modules/react-p5/build/index.js:3:30)
    at eval (webpack-internal:///(sc_server)/./node_modules/react-p5/build/index.js:4:2)
    at (sc_server)/./node_modules/react-p5/build/index.js (/home/hiroki/git_repository/zakuaku-summer-festival/.next/server/_sc_server_node_modules_react-p5_build_index_js.js:20:1)
    at __webpack_require__ (/home/hiroki/git_repository/zakuaku-summer-festival/.next/server/webpack-runtime.js:33:42)
    at __webpack_require__.t (/home/hiroki/git_repository/zakuaku-summer-festival/.next/server/webpack-runtime.js:73:38) {
  digest: undefined
}
null
```

This is my component code:

```ts
import dynamic from "next/dynamic";
import p5Types from "p5";

export default function Fireworks() {
    const Sketch = dynamic(
        import("react-p5").then((mod) => mod.default),
        { ssr: false }
    );

    function setup(p5: p5Types, canvasParentRef: Element) {
        p5.createCanvas(100, 100);
    }

    function draw(p5: p5Types) {
        p5.background(100, 100, 100);
    }

    return <Sketch setup={setup} draw={draw} />;
}
```

What should I do?

[Full code is here](https://github.com/toku-sa-n/zakuaku-summer-festival/tree/4b76bd2c0069f33cba3ab7ecab730e47b7be09f4). Please try running `npm run dev`.

Thank you.

**Comment by toku-sa-n** [comment]
Not sure if I understand the problem and the solution correctly, but it seems we have to add `"use client";` at the top of the files which use the component from Next.js 13.

```ts
"use client";

import Fireworks from "@/components/fireworks";

export default function Home() {
    return <Fireworks />;
}
```
